### ISSUE TITLE
Operacja Wyznacz najbliższe magazyny

### ISSUE THREAD

**Issue by mbrodowski** [monichimiuk/korona#4]
Utworzenie operacji:
Wyznacz najbliższe magazyny:
- Na wejściu lista OrderItem oraz adres miejsca docelowego (Geolocation- x, y)
- Na wyjściu lista OrderItem, ze wskazanymi WarehouseId

**Comment by monichimiuk** [comment]
**15-19 maja mnie nie ma**
data wykonania zadania:

- > optymistycznie do 14.05 EoD 
- > max do 23.05 EoD

**Comment by monichimiuk** [comment]
Done, po urlopie ulepszę walidacje i testy, ale core operacji działających już jest
