### ISSUE TITLE
Nowa operacja: zwróc geoLocation dla warehouse

### ISSUE THREAD

**Issue by mbrodowski** [monichimiuk/korona#5]
Nowa operacja: zwróć geoLocation dla warehouse
Zwróć informacje o magazynie

- Na wejściu warehouseID
- Na wyjściu GeoLocation magazynu

**Comment by tooomor** [comment]
20.05

**Comment by monichimiuk** [comment]
**15-19 maja mnie nie ma**
data wykonania zadania:

- > optymistycznie do 14.05 EoD 
- > max do 23.05 EoD

**Comment by monichimiuk** [comment]
Done
