### ISSUE TITLE
Niepoprawne wykorzystanie Optional

### ISSUE THREAD

**Issue by mbrodowski** [monichimiuk/korona#7]
https://github.com/monichimiuk/korona/blob/2a8aa044ce3387193fdd38d9ac772f547f87b657/src/main/java/dev/onichimiuk/marcin/warehouse/WarehouseServlet.java#L48

Niepoprawne wykorzystanie Optional. Proszę zmienić na orElse

**Comment by monichimiuk** [comment]
Optionalem jest magazyn zwracany z getWarehouseById z serwisu, ale później po prostu jest poprawna konstrukcja if/else na zwrócenie ResponeEntity w zależności od tego czy taki magazyn istnieje czy nie. Może na szybko przeoczyłeś? Daj znać :P

**Comment by monichimiuk** [comment]
Optionalem jest magazyn zwracany z getWarehouseById z serwisu, ale później po prostu jest poprawna konstrukcja if/else na zwrócenie ResponeEntity w zależności od tego czy taki magazyn istnieje czy nie. Może na szybko przeoczyłeś? Daj znać :P
